title: Ben DeVries
description: Remote sensing scientist interested in land cover change

url: http://bendevries.ca
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Publications
   url: /publications.html
 - title: Code
   url: /code.html
 - title: Contact
   url: /contact.html

social:
   github: bendv
   twitter: onchante
   soundcloud: bdv
   email: devries.br@gmail.com

google_analytics: "UA-72637604-1"
