title: Ben DeVries
description: Remote sensing scientist interested in land cover change

url: http://bendevries.ca
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Publications
   url: /publications
 - title: Code
   url: /code
 - title: Contact
   url: /contact

social:
   github: bendv
   twitter: onchante
   soundcloud: bdv
   email: devries.br@gmail.com

google_analytics: "UA-72637604-1"
