# Site settings
title: Ben DeVries
email: bdv@umd.edu
description: > # this means to ignore newlines until "baseurl:"
  Assistant Research Professor at the Department of Geographical Sciences, University of Maryland
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bendevries.ca" # the base hostname & protocol for your site
twitter_username: onchante
github_username:  bendv

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Research Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
