# Site settings
title: Ben DeVries
email: devries.br@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Researcher in land cover change monitoring using satellite time series data
baseurl: # the subpath of your site, e.g. /blog/
url: # the base hostname & protocol for your site
twitter_username: onchante  
github_username:  bendv

# Build settings
markdown: kramdown
